language: php
 
php:
  - 5.3

branches:
  only:
    - TESTS
 
before_script:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "mysql -e 'CREATE DATABASE cakephp_default;'"
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - sh -c "mysql -e 'CREATE TABLE cakephp_default.personas (
    id char(36) NOT NULL PRIMARY KEY,
    created datetime NOT NULL,
    modified datetime NOT NULL,
    name varchar(50) DEFAULT NULL,
    email varchar(50) NOT NULL,
    password char(40) NOT NULL,
    enabled tinyint(1) unsigned NOT NULL DEFAULT 1,
    confirmed tinyint(1) unsigned NOT NULL DEFAULT 0,
    is_admin tinyint(1) unsigned NOT NULL DEFAULT 0
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'"
  - sh -c "mysql -e 'CREATE TABLE cakephp_default.sections (
    id char(36) NOT NULL PRIMARY KEY,
    created datetime NOT NULL,
    modified datetime NOT NULL,
    name varchar(100) NOT NULL,
    published tinyint(1) unsigned NOT NULL DEFAULT 1
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'"
  - sh -c "mysql -e 'CREATE TABLE cakephp_default.products (
    id char(36) NOT NULL PRIMARY KEY,
    created datetime NOT NULL,
    modified datetime NOT NULL,
    name varchar(100) NOT NULL,
    published tinyint(1) unsigned NOT NULL DEFAULT 1,
    section_id char(36) NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;'"
  - sh -c "mysql -e 'INSERT INTO cakephp_default.personas(id, created, modified, name, email, password, enabled, confirmed, is_admin) VALUES (UUID(), CURRENT_DATE, CURRENT_DATE, \"Luis Carlos Osorio Jayk\", \"luiscarlosjayk@gmail.com\", MD5(\"123456\"), 1, 1, 1)'"
  - sh -c "mysql -e 'INSERT INTO cakephp_default.sections(id, created, modified, name, published) VALUES(\"5155ada6-d970-4f18-92cd-0a8882e7320b\", CURRENT_DATE, CURRENT_DATE, \"verduras\", 1)'"
  - sh -c "mysql -e 'INSERT INTO cakephp_default.sections(id, created, modified, name, published) VALUES(\"5155b5c8-5844-466c-8489-0a8882e7320b\", CURRENT_DATE, CURRENT_DATE, \"frutas\", 1)'"
  - sh -c "mysql -e 'INSERT INTO cakephp_default.products(id, created, modified, name, published, section_id) VALUES(UUID(), CURRENT_DATE, CURRENT_DATE, \"tomate\", 1, \"5155ada6-d970-4f18-92cd-0a8882e7320b\")'"
  - sh -c "mysql -e 'INSERT INTO cakephp_default.products(id, created, modified, name, published, section_id) VALUES(UUID(), CURRENT_DATE, CURRENT_DATE, \"manzana\", 1, \"5155b5c8-5844-466c-8489-0a8882e7320b\")'"
  - echo "<?php
    class DATABASE_CONFIG {
    public \$default = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_default',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'password' => '',
      'persitent' => false
    ),
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis'
      'password' => '',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php
 
script:
  - ./lib/Cake/Console/cake test core Core/Configure --stderr